apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-224608-1g9n-service
spec:
  selector:
    app: enterprise-system-224608-1g9n
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
